# Generated by Django 5.0.6 on 2024-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('posted_date', models.DateField()),
                ('engine_capacity', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('steering', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('manufacture_year', models.IntegerField()),
                ('import_year', models.IntegerField()),
                ('drive', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('lease', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('drive_type', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('doors', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('unique_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
