# Generated by Django 5.0.6 on 2024-05-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_retrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='doors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='drive',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='drive_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='engine_capacity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='import_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='interior_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='lease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='license_plate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='manufacture_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='mileage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='posted_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='steering',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='transmission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
