# Generated by Django 5.0.6 on 2024-06-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_retrive', '0002_alter_cardata_address_alter_cardata_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cardata',
            name='lease',
        ),
    ]
