# Generated by Django 5.0.6 on 2024-06-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uildverlegch', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('motor_bagtaamj', models.IntegerField()),
                ('xrop', models.IntegerField()),
                ('joloo', models.IntegerField()),
                ('uildverlesen_on', models.IntegerField()),
                ('orj_irsen_on', models.IntegerField()),
                ('hudulguur', models.IntegerField()),
                ('hutlugch', models.IntegerField()),
                ('yavsan_km', models.IntegerField()),
                ('une', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uildverlegch', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('motor_bagtaamj', models.IntegerField()),
                ('xrop', models.IntegerField()),
                ('joloo', models.IntegerField()),
                ('uildverlesen_on', models.IntegerField()),
                ('orj_irsen_on', models.IntegerField()),
                ('hudulguur', models.IntegerField()),
                ('hutlugch', models.IntegerField()),
                ('yavsan_km', models.IntegerField()),
                ('une', models.FloatField()),
            ],
        ),
    ]
