# Generated by Django 5.0.6 on 2024-06-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_to_My_AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='hudulguur',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='hutlugch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='joloo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='mark',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='motor_bagtaamj',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='orj_irsen_on',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='uildverlegch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='uildverlesen_on',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='xrop',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='yavsan_km',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='hudulguur',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='hutlugch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='joloo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='mark',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='motor_bagtaamj',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='orj_irsen_on',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='uildverlegch',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='uildverlesen_on',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='xrop',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='yavsan_km',
            field=models.BigIntegerField(),
        ),
    ]
