# Generated by Django 5.0.6 on 2024-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_AI', '0003_hudulguur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joloo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Зөв'), (0, 'Буруу')]),
        ),
        migrations.AlterField(
            model_name='xrop',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Автомат'), (0, 'Механик')]),
        ),
    ]
