# Generated by Django 5.0.6 on 2024-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_AI', '0004_alter_joloo_type_alter_xrop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hudulguur',
            name='type',
            field=models.CharField(choices=[(0, 'Бензин'), (1, 'Газ'), (2, 'Дизель'), (3, 'Хайбрид'), (4, 'Цахилгаан')], max_length=100),
        ),
    ]
