# Generated by Django 5.0.6 on 2024-06-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_AI', '0005_alter_hudulguur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hudulguur',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Бензин'), (1, 'Газ'), (2, 'Дизель'), (3, 'Хайбрид'), (4, 'Цахилгаан')]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orjirsenon',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='uildverlesenon',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
